[project]
name = "kyoukagakusyu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.4",
    "torch>=2.6.0",
    "torchvision>=0.21.0",
]
